name: flutter_ai_providers
description: Community-contributed providers for the Flutter AI Toolkit.
version: 0.3.4
repository: https://github.com/davidmigloz/flutter_ai_community/tree/main/packages/flutter_ai_providers
issue_tracker: https://github.com/davidmigloz/flutter_ai_community/issues

topics:
  - ai
  - chat
  - llms

environment:
  sdk: ^3.5.0
  flutter: ">=3.27.0"

dependencies:
  llama_sdk: ^0.0.4
  anthropic_sdk_dart: ^0.2.0+1
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^0.9.1
  ollama_dart: ^0.2.2+1
  openai_dart: ^0.5.4
  http: ^1.3.0
  dartantic_ai: ^1.0.1
  dartantic_interface: ^1.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
