name: flutter_ai_providers
description: Community-contributed providers for the Flutter AI Toolkit.
version: 0.2.0
repository: https://github.com/davidmigloz/flutter_ai_community/tree/main/packages/flutter_ai_providers
issue_tracker: https://github.com/davidmigloz/flutter_ai_community/issues

topics:
  - ai
  - chat
  - llms

environment:
  sdk: ^3.5.0
  flutter: '>=3.27.0'

dependencies:
  llama_sdk: ^0.0.4
  anthropic_sdk_dart: ^0.2.0+1
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^0.6.7
  ollama_dart: ^0.2.2+1
  openai_dart: ^0.4.5
  http: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
